import "dotenv/config";
import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const siteName = process.env.SITE_NAME ?? "Critiqo";
const baseUrl = (process.env.SITE_URL ?? "http://localhost:3000").replace(
  /\/+$/,
  "",
);
const defaultOgImage =
  process.env.SEO_DEFAULT_OG_IMAGE ?? `${baseUrl}/images/default-og.png`;
const defaultDescription =
  process.env.SEO_DEFAULT_DESCRIPTION ??
  "Discover trusted product reviews, compare experiences, and make informed buying decisions.";
const legacyGeneratedDescriptionPattern = new RegExp(
  ["Generated by ", "create next app"].join(""),
  "gi",
);
const cleanDefaultDescription = defaultDescription.replace(
  legacyGeneratedDescriptionPattern,
  "Discover trusted product reviews with Critiqo.",
);
const defaultTitle =
  process.env.SEO_DEFAULT_TITLE ?? "Critiqo | Trusted Product Reviews";

const defaultOrganizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: siteName,
  url: baseUrl,
  logo: defaultOgImage,
};

const pages = [
  {
    slug: "home",
    path: "",
    title: "Honest Product Reviews and Buying Advice",
    seoTitle: "Honest Product Reviews | Critiqo",
    description:
      "Explore honest product reviews, compare real experiences, and find the right products with Critiqo.",
    keyword: "product reviews",
    html: "<h1>Honest Product Reviews</h1><p>Explore product reviews and trusted buying advice from the Critiqo community.</p>",
    schema: {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: siteName,
      url: baseUrl,
      description: cleanDefaultDescription,
    },
  },
  {
    slug: "about",
    path: "about",
    title: "About Critiqo",
    seoTitle: "About Critiqo | Our Review Community",
    description:
      "Learn how Critiqo helps people share product experiences and make more informed decisions.",
    keyword: "about Critiqo",
    html: '<h1>About Critiqo</h1><p>Critiqo helps people make informed decisions through useful product reviews. <a href="/contact">Contact our team</a>.</p>',
    schema: defaultOrganizationSchema,
  },
  {
    slug: "contact",
    path: "contact",
    title: "Contact Critiqo",
    seoTitle: "Contact Critiqo | Get in Touch",
    description:
      "Contact the Critiqo team with questions, feedback, or support requests.",
    keyword: "contact Critiqo",
    html: "<h1>Contact Critiqo</h1><p>Get in touch with the Critiqo team for help, feedback, or other questions.</p>",
    schema: defaultOrganizationSchema,
  },
  {
    slug: "blog",
    path: "blog",
    title: "Product Guides and Insights",
    seoTitle: "Product Guides and Insights | Critiqo Blog",
    description:
      "Read practical product guides, comparisons, and insights from the Critiqo community.",
    keyword: "product guides",
    html: "<h1>Product Guides and Insights</h1><p>Explore useful product guides and insights from Critiqo.</p>",
    schema: {
      "@context": "https://schema.org",
      "@type": "Blog",
      name: "Critiqo Blog",
      url: `${baseUrl}/blog`,
    },
  },
  {
    slug: "reviews",
    path: "reviews",
    title: "Community Product Reviews",
    seoTitle: "Community Product Reviews | Critiqo",
    description:
      "Browse community product reviews and compare first-hand experiences before you buy.",
    keyword: "community product reviews",
    html: "<h1>Community Product Reviews</h1><p>Browse product reviews and compare real customer experiences.</p>",
    schema: {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: "Community Product Reviews",
      url: `${baseUrl}/reviews`,
    },
  },
] as const;

const legacyBrandPattern = new RegExp(
  `${["opinion", "oasis"].join("")}|${["e", "tutor"].join("")}`,
  "gi",
);

const replaceLegacyValues = (value: string): string =>
  value
    .replace(/\/contactus\b/gi, "/contact")
    .replace(
      legacyGeneratedDescriptionPattern,
      "Discover trusted products with Critiqo",
    )
    .replace(legacyBrandPattern, "Critiqo");

const replaceLegacyContent = async (): Promise<void> => {
  const [existingPages, blogPosts, reviews, oldPosts, categories, seoMeta] =
    await Promise.all([
      prisma.page.findMany(),
      prisma.blogPost.findMany(),
      prisma.review.findMany(),
      prisma.post.findMany(),
      prisma.category.findMany(),
      prisma.seoMeta.findMany(),
    ]);

  await Promise.all([
    ...existingPages.flatMap((page) => {
      const title = replaceLegacyValues(page.title);
      const html = replaceLegacyValues(page.contentHtml);
      return title !== page.title || html !== page.contentHtml
        ? [
            prisma.page.update({
              where: { id: page.id },
              data: { title, contentHtml: html },
            }),
          ]
        : [];
    }),
    ...blogPosts.flatMap((post) => {
      const title = replaceLegacyValues(post.title);
      const html = replaceLegacyValues(post.contentHtml);
      return title !== post.title || html !== post.contentHtml
        ? [
            prisma.blogPost.update({
              where: { id: post.id },
              data: { title, contentHtml: html },
            }),
          ]
        : [];
    }),
    ...reviews.flatMap((review) => {
      const title = replaceLegacyValues(review.title);
      const description = replaceLegacyValues(review.description);
      const html = review.contentHtml
        ? replaceLegacyValues(review.contentHtml)
        : review.contentHtml;
      return title !== review.title ||
        description !== review.description ||
        html !== review.contentHtml
        ? [
            prisma.review.update({
              where: { id: review.id },
              data: { title, description, contentHtml: html },
            }),
          ]
        : [];
    }),
    ...oldPosts.flatMap((post) => {
      const title = replaceLegacyValues(post.title);
      const description = replaceLegacyValues(post.description);
      return title !== post.title || description !== post.description
        ? [
            prisma.post.update({
              where: { id: post.id },
              data: { title, description },
            }),
          ]
        : [];
    }),
    ...categories.flatMap((category) => {
      let name = replaceLegacyValues(category.name);
      if (
        name !== category.name &&
        categories.some((candidate) =>
          candidate.id !== category.id
            ? replaceLegacyValues(candidate.name).toLowerCase() ===
              name.toLowerCase()
            : false,
        )
      ) {
        name = `${name} ${category.id.slice(0, 8)}`;
      }
      return name !== category.name
        ? [
            prisma.category.update({
              where: { id: category.id },
              data: { name },
            }),
          ]
        : [];
    }),
    ...seoMeta.flatMap((meta) => {
      const updates: Prisma.SeoMetaUpdateInput = {};
      for (const field of [
        "seoTitle",
        "metaDescription",
        "slug",
        "canonicalUrl",
        "focusKeyword",
        "ogTitle",
        "ogDescription",
        "ogImage",
        "twitterTitle",
        "twitterDescription",
        "twitterImage",
      ] as const) {
        const current = meta[field];
        if (current) {
          const updated = replaceLegacyValues(current);
          if (updated !== current) updates[field] = updated;
        }
      }
      return Object.keys(updates).length > 0
        ? [prisma.seoMeta.update({ where: { id: meta.id }, data: updates })]
        : [];
    }),
  ]);
};

const seedSeoPages = async (): Promise<void> => {
  await prisma.siteSettings.upsert({
    where: { id: "default" },
    create: {
      id: "default",
      siteName,
      baseUrl,
      defaultTitle,
      defaultDescription: cleanDefaultDescription,
      defaultOgImage,
    },
    update: {
      siteName,
      baseUrl,
      defaultTitle,
      defaultDescription: cleanDefaultDescription,
      defaultOgImage,
    },
  });

  for (const page of pages) {
    const canonicalUrl = page.path ? `${baseUrl}/${page.path}` : `${baseUrl}/`;
    const savedPage = await prisma.page.upsert({
      where: { slug: page.slug },
      create: {
        slug: page.slug,
        title: page.title,
        contentHtml: page.html,
        published: true,
      },
      update: {
        title: page.title,
        contentHtml: page.html,
        published: true,
      },
    });

    await prisma.$transaction(async (tx) => {
      await tx.seoMeta.upsert({
        where: { pageId: savedPage.id },
        create: {
          pageId: savedPage.id,
          slug: page.slug,
          seoTitle: page.seoTitle,
          metaDescription: page.description,
          focusKeyword: page.keyword,
          canonicalUrl,
          noindex: false,
          ogTitle: page.seoTitle,
          ogDescription: page.description,
          ogImage: defaultOgImage,
          twitterTitle: page.seoTitle,
          twitterDescription: page.description,
          twitterImage: defaultOgImage,
        },
        update: {
          slug: page.slug,
          seoTitle: page.seoTitle,
          metaDescription: page.description,
          focusKeyword: page.keyword,
          canonicalUrl,
          noindex: false,
          ogTitle: page.seoTitle,
          ogDescription: page.description,
          ogImage: defaultOgImage,
          twitterTitle: page.seoTitle,
          twitterDescription: page.description,
          twitterImage: defaultOgImage,
        },
      });
      await tx.schemaMarkup.deleteMany({ where: { pageId: savedPage.id } });
      await tx.schemaMarkup.create({
        data: {
          pageId: savedPage.id,
          type: page.schema["@type"],
          json: page.schema,
        },
      });
    });
  }

  const legacyContactPage = await prisma.page.findUnique({
    where: { slug: "contactus" },
    select: { id: true },
  });
  if (legacyContactPage) {
    await prisma.$transaction([
      prisma.page.update({
        where: { id: legacyContactPage.id },
        data: { published: false },
      }),
      prisma.seoMeta.updateMany({
        where: { pageId: legacyContactPage.id },
        data: {
          slug: "contact",
          canonicalUrl: `${baseUrl}/contact`,
          noindex: true,
        },
      }),
    ]);
  }
};

const seed = async (): Promise<void> => {
  await replaceLegacyContent();
  await seedSeoPages();
};

seed()
  .catch((error: unknown) => {
    console.error("Failed to seed SEO content:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
